import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchItems , addItem ,updateItem , deleteItem  } from './cartAPI';

const initialState = {
  items: [],
  status: 'idle',
};

// typically used to make async requests.
export const fetchAsync = createAsyncThunk(
  'cart/fetchItems',
  async () => {
    const response = await fetchItems();
    const data = await response.json()
    return data.cart.items
  }
);


export const addAsync = createAsyncThunk(
  'cart/addItems',
  async (item) => {
    const response = await addItem(item);
    const data = await response.json();
    return data.data;
   
  }
);

export const updateAsync = createAsyncThunk(
  'cart/updateItems',
  async ({itemId , count} )  => {
    const response = await updateItem({itemId , count});
    const data = await response.json();
    return data.data
    // The value we return becomes the `fulfilled` action payload
    // return response.data;
  }
);

export const deleteAsync = createAsyncThunk(
  'cart/deleteItems',
  async ({itemId} )  => {
    const response = await deleteItem({itemId});
    const data = await response.json();
    return itemId
   
  }
);

export const cartSlice = createSlice({
  name: 'cart',
  initialState,
  reducers: {
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAsync.fulfilled , (state , action) =>{
        state.items = action.payload;
        
      })
      .addCase(addAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        const index = 
        state.items.push(
          {quantity:action.payload.quantity , 
          product:action.payload.product[0]}
          
          )
      })
      .addCase(updateAsync.fulfilled, (state, action) => {
        state.status = 'idle';

        const index = state.items.findIndex((item)=>item.product._id.toString() ===action.payload.product[0]._id.toString())
     
        state.items[index].quantity=action.payload.quantity
      })
      // .addCase(updateAsync.pending , (state,action)=>{
      //   state.status = 'loading';
      //   state.items=state.items
      // })

      .addCase(deleteAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        const index = state.items.findIndex((item)=>item.product.id.toString() ===action.payload.toString())
        console.log(index)
        state.items.splice(index,1);
      })
  },
});



export default cartSlice.reducer;